stages:
  - vet
  - test
  - qa

.nodejs: &nodejs
  image: node:11.9.0
  cache:
    paths:
      - node_modules
  except:
    - tags

lint:
  stage: vet
  <<: *nodejs
  variables:
    NODE_ENV: development
  before_script:
    - node --version
    - npm install --global npm
    - npm --version
    - npm install
  script:
    - make lint

unit-test:
  stage: test
  <<: *nodejs
  variables:
    NODE_ENV: test
  before_script:
    - node --version
    - npm install --global npm
    - npm --version
    - npm install
  script:
    - make test

coverage:
  stage: qa
  <<: *nodejs
  variables:
    NODE_ENV: test
  before_script:
    - node --version
    - npm install --global npm
    - npm --version
    - npm install
  script:
    - make test:coverage
