stages:
  - vet

.nodejs: &nodejs
  image: node:11.9.0
  cache:
    paths:
      - node_modules
  before_script:
    - node --version
    - npm install --global npm
    - npm --version
    - npm install
  except:
    - tags

lint-typescript:
  stage: vet
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - make verify:lint:ts

lint-stylus:
  stage: vet
  <<: *nodejs
  variables:
    NODE_ENV: development
  script:
    - make verify:lint:styl
