stages:
  - vet

.nodejs: &nodejs
  image: node:11.9.0
  cache:
    paths:
      - node_modules
  except:
    - tags

lint:
  stage: vet
  <<: *nodejs
  variables:
    NODE_ENV: development
  before_script:
    - node --version
    - npm install --global npm
    - npm --version
    - npm install
  script:
    - make lint
